const catalogData = {
    categories: [
        { id: "cementos", name: "Cementos y Cales", image: "img/categories/cat-cementos.webp", icon: "fa-cubes", description: "Cementos portland, de albañilería y cales hidráulicas y aéreas." },
        { id: "aridos", name: "Áridos", image: "img/categories/cat-aridos.png", icon: "fa-mountain", description: "Arena de río, piedra partida 6/20, cascote granza y mezclas." },
        { id: "ladrillos", name: "Ladrillos y Bloques", image: "img/categories/cat-ladrillos.webp", icon: "fa-border-all", description: "Ladrillos comunes, cerámicos huecos, portantes y bloques de hormigón/Retak." },
        { id: "hierros", name: "Hierros y Acero", image: "img/categories/cat-hierros.png", icon: "fa-bars-staggered", description: "Barras ADN 420 (6mm a 25mm), mallas electrosoldadas y alambres." },
        { id: "adhesivos", name: "Adhesivos y Pastinas", image: "img/categories/cat-adhesivos.jpg", icon: "fa-fill-drip", description: "Pegamentos Weber/Klaukol para cerámicas y porcelanatos, pastinas y aditivos." },
        { id: "aislantes", name: "Hidrófugos e Impermeabilizantes", icon: "fa-shield-halved", description: "Ceresita, hidrófugos de masa, membranas asfálticas y emulsiones." },
        { id: "pinturas", name: "Pinturas y Revestimientos", icon: "fa-paint-roller", description: "Látex exterior e interior, fijadores selladores y enduidos." },
        { id: "chapas", name: "Chapas y Techos", icon: "fa-house-chimney", description: "Chapas sinusoidales, trapezoidales, perfiles y aislaciones térmicas." }
    ],
    products: [
        { id: "01005", category: "cementos", name: "Cemento Avellaneda CPC40", image: "img/products/cemento-avellaneda.webp", description: "Cemento portland compuesto de alta resistencia para uso general y estructural.", brand: "Cementos Avellaneda", features: ["Bolsa 25 kg / 50 kg", "Norma IRAM 50000", "Uso estructural y general"] },
        { id: "01113", category: "cementos", name: "Hidralit Cemento de Albañilería", image: "img/products/hidralit.webp", description: "Cemento plástico y trabajable ideal para morteros de asiento, revoques y contrapisos.", brand: "Cementos Avellaneda", features: ["Bolsa 20 kg", "Excelente trabajabilidad", "No apto uso estructural"] },
        { id: "02005", category: "cementos", name: "Cal Hidrat Extra para Albañilería", image: "img/products/cal-hidrat-extra.webp", description: "Cal hidráulica hidratada de alto rendimiento para mezclas de asiento y revoques gruesos.", brand: "Cementos Avellaneda", features: ["Bolsa 25 kg", "Máxima plasticidad"] },
        { id: "02120", category: "cementos", name: "Cal Aérea El Milagro Calidad Superior", image: "img/products/cal-el-milagro.webp", description: "Cal aérea hidratada en polvo de máxima pureza para revoques finos y enlucidos.", brand: "El Milagro / Calidra", features: ["Bolsa 25 kg", "San Juan", "Blancura y fineza superior"] },
        { id: "03000", category: "aridos", name: "Arena de Río Limpia a Granel / Bolsón", image: "img/products/arena-granel.jpg", description: "Arena clasificada y lavada libre de impurezas para hormigones, revoques y mezclas.", brand: "Granel / Bolsón", features: ["Por m³ o bolsón de 1m³", "Seca y limpia"] },
        { id: "03300", category: "aridos", name: "Piedra Partida 6/20", image: "img/products/piedra-partida.jpg", description: "Piedra partida granítica seleccionada para hormigón armado y contrapisos.", brand: "Granel / Bolsón", features: ["Granulometría 6/20", "Por m³ o bolsón"] },
        { id: "03500", category: "aridos", name: "Bolsón de Áridos (Arena / Piedra / Cascote)", image: "img/products/bolson-aridos.png", description: "Bolsón reforzado big bag de 1 m³ para entrega limpia y acopio ordenado en obra.", brand: "Bolsón Big Bag", features: ["Capacidad 1 m³", "Fácil descarga en vereda u obra"] },
        { id: "05006", category: "ladrillos", name: "Ladrillo Hueco 8x18x33 (Tabique)", image: "img/products/ladrillo-8x18x33.webp", description: "Ladrillo cerámico hueco 6 agujeros para tabiques divisorios internos.", brand: "Fanelli / Ctibor", features: ["Medida 8x18x33 cm", "6 agujeros", "Rendimiento 16 u/m²"] },
        { id: "05010", category: "ladrillos", name: "Ladrillo Hueco 12x18x33 (Muro Estándar)", image: "img/products/ladrillo-12x18x33.webp", description: "Ladrillo cerámico hueco 9 agujeros para muros y cerramientos tradicionales.", brand: "Fanelli / Ctibor", features: ["Medida 12x18x33 cm", "9 agujeros", "Rendimiento 16 u/m²"] },
        { id: "05012", category: "ladrillos", name: "Ladrillo Hueco 18x18x33 (Cerramiento)", image: "img/products/ladrillo-18x18x33.webp", description: "Ladrillo cerámico hueco 12 agujeros para muros exteriores con alta aislación acústica y térmica.", brand: "Fanelli / Ctibor", features: ["Medida 18x18x33 cm", "12 agujeros", "Aislación térmica"] },
        { id: "06012", category: "ladrillos", name: "Ladrillo Portante 12x19x33", image: "img/products/ladrillo-portante-12.webp", description: "Ladrillo cerámico portante para muros resistentes sin necesidad de columnas intermedias.", brand: "Fanelli / Ctibor", features: ["Medida 12x19x33 cm", "Estructural portante", "Rendimiento 16 u/m²"] },
        { id: "06018", category: "ladrillos", name: "Ladrillo Portante 18x19x33", image: "img/products/ladrillo-portante-18.webp", description: "Ladrillo cerámico portante de 18 cm de espesor para muros de carga perimetrales.", brand: "Fanelli / Ctibor", features: ["Medida 18x19x33 cm", "Máxima resistencia mecánica"] },
        { id: "09001", category: "hierros", name: "Barra Hierro ADN 420 - 6 mm a 25 mm", image: "img/categories/cat-hierros.png", description: "Barras de acero conformadas de dureza natural para estructuras de hormigón armado.", brand: "Acindar", features: ["Barras 12 metros", "Norma IRAM-IAS U 500-06"] },
        { id: "09011", category: "hierros", name: "Malla Sima Electrosoldada R-084", image: "img/categories/cat-hierros.png", description: "Malla de acero para losas, plateas de fundación y pisos industriales.", brand: "Acindar", features: ["Panel 2 x 5 mts", "Cuadrícula 15x25 cm"] },
        { id: "11100", category: "adhesivos", name: "Weber Impermeable Adhesivo Cerámico", image: "img/categories/cat-adhesivos.jpg", description: "Mortero adhesivo con aditivo hidrófugo para cerámicos en interiores y exteriores.", brand: "Weber / Saint-Gobain", features: ["Bolsa 30 kg", "Impermeable"] },
        { id: "11104", category: "adhesivos", name: "Weber Porcelanato Pro Flexible", image: "img/categories/cat-adhesivos.jpg", description: "Pegamento de alta performance para placas de porcelanato de baja absorción.", brand: "Weber / Saint-Gobain", features: ["Bolsa 30 kg", "Alta flexibilidad y adherencia"] }
    ]
};
